import React, {useState} from 'react';
import {Text, View, StyleSheet, Alert} from 'react-native';
import NumberContainer from '../components/NumberContainer';
import Title from '../components/Title';
import PrimaryButton from '../components/PrimaryButton';

type GameScreenProps = {
  userNumber: number;
};

let minGuessBoundary = 1;
let maxGuessBoundary = 100;

function GameScreen(props: GameScreenProps) {
  const initialGuess = generateRandomBetween(1, 100, [props.userNumber]);
  const [currentGuess, setCurrentGuess] = useState(initialGuess);

  function nextGuessHandler(direction: 'lower' | 'greater') {
    /* Logic to make sure the user is not cheating */
    if (
      (direction === 'lower' && currentGuess < props.userNumber) ||
      (direction === 'greater' && currentGuess > props.userNumber)
    ) {
      Alert.alert("Don't Lie!", 'You know that this is wrong...', [
        {
          text: 'Sorry!',
          style: 'cancel',
        },
      ]);
      return;
    }

    if (direction === 'lower') {
      maxGuessBoundary = currentGuess;
    } else {
      /* We add + 1 here because the value generated by Math.random() is inclusive to the min range value [0, 1) */
      minGuessBoundary = currentGuess + 1;
    }

    const newRandomNumber = generateRandomBetween(
      minGuessBoundary,
      maxGuessBoundary,
      [currentGuess],
    );
    setCurrentGuess(newRandomNumber);
  }

  return (
    <View style={styles.screen}>
      <Title title="Opponent's Guess" />
      <NumberContainer text={currentGuess} />
      <View>
        <Text>Higher or lower?</Text>
        <View>
          <PrimaryButton
            textValue="-"
            onPress={() => nextGuessHandler('lower')}
          />
          <PrimaryButton
            textValue="+"
            onPress={() => nextGuessHandler('greater')}
          />
        </View>
      </View>
      {/* <View>LOG ROUNDS</View> */}
    </View>
  );
}

export default GameScreen;

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    padding: 24,
    top: '5%',
  },
});

function generateRandomBetween(min: number, max: number, exclude: number[]) {
  const randomNumber = Math.floor(Math.random() * (max - min)) + min;

  if (exclude.find((number) => number === randomNumber)) {
    return generateRandomBetween(min, max, exclude);
  } else {
    return randomNumber;
  }
}
